set-option -sa terminal-overrides ',xterm-256color:RGB'
set -g default-shell /bin/zsh
set -g @shell_mode 'vi'
set -gq allow-passthrough on

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \\
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h "select-pane -L"
bind-key -n C-j "select-pane -D"
bind-key -n C-k "select-pane -U"
bind-key -n C-l "select-pane -R"
bind-key -n C-\\ if-shell "$is_vim" "send-keys C-\\\\" "select-pane -l"
bind-key -n C-Space if-shell "$is_vim" "send-keys C-Space"
